/***********************************************************************/
/*                                                                     */
/*  FILE        :test3.c                                               */
/*  DATE        :Wed, Jun 25, 2014                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include <kernel.h>
#include "ssp/kernel_cfg.h"

#include <machine.h>					// Include machine.h
#include "iodefine.h"					// Include iodefine.h
                  
                  
#include<stdio.h>

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

//void main(void)
//{
//	printf("hello\n");
//}

int flag;
volatile int count = 0;

void setup()
{



	PORT1.DDR.BIT.B5 = 1;				// P15 is Output
	MSTP( CMT0 ) = 0;					// Wakeup CMT0,CMT1
//	CMT0.CMCOR = 48000000/512/2 - 1;	// CMCOR is 500ms Count 
	CMT0.CMCOR = 48000000/512/2/500 - 1;	// CMCOR is 1ms Count 
	CMT0.CMCR.WORD = 0x0043;			// CMIE is Enable,CKS is PCLK/512
	IEN( CMT0, CMI0 ) = 1;				// CMI0 Enable
	IPR( CMT0, CMI0 ) = 1;				// CMI0 Interrupt Level is 1
//	set_psw( 0x00010000 );				// Set I=1, IPL=0 of PSW
	CMT.CMSTR0.BIT.STR0 = 1;			// Start CMT0
	
}
void main(intptr_t arg)
{
	printf("main here\n");
	setup();
	act_tsk(TASK3_ID);
	act_tsk(TASK2_ID);	
	printf("main end\n");
}

void task2(intptr_t arg)
{
	for(;;)
	{
		printf("task2 count = %d\n",count);
		dly_tsk(500);
	}
}


void CMI0(void)							// Interrupt Function
{										// Multiple Interrupt Enable
//	PORT1.DR.BIT.B5 ^= 1;				// Reverse P15(LED)
////		CMT.CMSTR0.BIT.STR0 = 0;			// Start CMT0
//	iact_tsk(TASK2_ID);
	isig_tim();
}

void task3(void)
{
	printf("task3-----------------\n");
	for(;;)
	{
		count++;
	}
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
